### ISSUE TITLE
Syntax Error in Reqs

### ISSUE THREAD

**Issue by johntomczak** [DiegoAgher/learnPongPython#5]
Hey, I think you need to hyphenate the scikit learn line. It failed to pip for me at first, but when I looked and changed it to the way I have made other reqs.txt docs, it worked.

Currently reads as `scikitlearn==0.19.1` but I think it needs to be `scikit-learn==0.19.1`

**Comment by DiegoAgher** [comment]
You are right! thanks for pointing that out @johntomczak !
